apiVersion: v2
name: dead-drop
description: Client-side encrypted secret sharing service
type: application
version: 0.1.5
appVersion: "0.1.5"
keywords:
  - encryption
  - secrets
  - kubernetes
  - postgres
